# Generated by Django 4.2.8 on 2023-12-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chat_id', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_anonymous_contact', models.BooleanField(default=False)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('superuser', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
