# Generated by Django 4.2.8 on 2023-12-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='silent_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
